In [ ]:
import requests
import pandas as pd

In [ ]:
link = 'https://data.nantesmetropole.fr/api/records/1.0/search/?dataset=244400404_stations-velos-libre-service-nantes-metropole-disponibilites&q=&facet=banking&facet=bonus&facet=status&facet=contract_name'
r = requests.get(link)
pd.json_normalize(r.json())

   nhits  ... parameters.timezone
0    127  ...                 UTC

[1 rows x 9 columns]

In [ ]:
my_data_frame = pd.json_normalize(r.json(),  record_path= ["records"])[["fields.address", "fields.available_bikes", "fields.bike_stands"]]

my_data_frame

                                     fields.address  ...  fields.bike_stands
0      2, rue de Gigant - Place de l'Edit de Nantes  ...                  13
1                                               NaN  ...                   5
2           Rue de la Loire - place Gaston Defferre  ...                  22
3  Allée de la Bourse - Boulevard des Nations-Unies  ...                  22
4                             10, rue des Olivettes  ...                  15
5                Rue de Berry - Rue des Hauts Pavés  ...                  16
6                         16, boulevard Jules Verne  ...                  30
7                                 18, rue du Moulin  ...                  15
8                           8, rue de l'Arche Sèche  ...                  14
9        25, quai de Versailles - Ile de Versailles  ...                  15

[10 rows x 3 columns]

In [ ]:
my_data_frame["taux_remplissage"] = my_data_frame["fields.available_bikes"] / my_data_frame["fields.bike_stands"]
my_data_frame.rename(columns={'fields.address': 'adresse'}, inplace=True)
my_data_frame.drop(['fields.available_bikes', 'fields.bike_stands'], axis=1, inplace=True)
my_data_frame

                                            adresse  taux_remplissage
0      2, rue de Gigant - Place de l'Edit de Nantes          0.000000
1                                               NaN          0.000000
2           Rue de la Loire - place Gaston Defferre          0.409091
3  Allée de la Bourse - Boulevard des Nations-Unies          0.363636
4                             10, rue des Olivettes          0.733333
5                Rue de Berry - Rue des Hauts Pavés          0.437500
6                         16, boulevard Jules Verne          0.400000
7                                 18, rue du Moulin          0.600000
8                           8, rue de l'Arche Sèche          0.571429
9        25, quai de Versailles - Ile de Versailles          0.400000

In [ ]:
import folium
m = folium.Map(location=[37.6, 14.2],zoom_start=7)
m